# https://taskfile.dev

version: '3'

vars:
  OK_COLOR: '\033[32;01m'
  NO_COLOR: '\033[0m'

tasks:
  help:
    desc: Show the list of commands
    cmds:
      - task --list-all

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run -c .golangci.yml

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  test:
    desc: Run tests
    cmds:
      - go test -gcflags=-l -covermode=atomic -race ./...

  build:
    deps:
      - tidy
      - test
    desc: Build service
    cmds:
      - GOOS=linux GOARCH=amd64 go build -buildvcs=false -ldflags="-s -w" -o bin/api-server ./cmd/server/main.go

  default:
    cmds:
      - task: help