---
global:
  scrape_interval: 5s #1m
  evaluation_interval: 5s #1m

alerting:

rule_files:

scrape_configs:
  - job_name: backend-service-template
    static_configs:
      # metric port. app - represents host+port. In docker-compose our service labeled as "app".
      - targets: ["app:8081"]