name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.22.2"

jobs:
  install-task:
    name: Install Task
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1

  install-go:
    name: Install Go
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go version


  lint:
    name: Linting
    needs:
      - install-go
      - install-task
    runs-on: ubuntu-latest
    permissions: read-all
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: lint
        uses: golangci/golangci-lint-action@v3
      - run: task lint

  test:
    name: Testing
    needs:
      - install-go
      - install-task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-cache
      - name: Test
        run: task test